spring:
  application:
    name: order-service
  profiles:
    active: local
  r2dbc:
    url: r2dbc:h2:mem:///ordersdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    pool:
      initial-size: 5
      max-size: 20
    initialization-mode: always
  main:
    web-application-type: reactive

server:
  port: 8080

idm:
  local:
    secrets:
      audit-service-base-url: http://localhost:8081
      audit-service-api-key: local-audit-key

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
